**

!package.json
!package-lock.json

!boards/
!boards/**

!packages/
!packages/core/
!packages/core/package.json
!packages/core/dist/
!packages/core/dist/**
!packages/server/
!packages/server/package.json
!packages/server/dist/
!packages/server/dist/**
!packages/web/
!packages/web/gateway-public/
!packages/web/gateway-public/**

!docker/
!docker/Dockerfile.gateway.runtime
